# For running locally

version: '3'
services:
  server:
    image: notifywatcher/server
    restart: on-failure
    environment:
      - DATABASE_HOST=mongo
      - PORT=80
      - GITHUB_NOTIFICATIONS_TOKEN=$GITHUB_NOTIFICATIONS_TOKEN
      - RUT=$RUT
      - NODE_ENV=development
    ports:
      - '3001:80'
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - './tmp/mongodb/db:/data/db'
